#!/bin/bash

# discbin: sends stdin to a discord webhook
# by thiefadjacent

hook="$1"
script_path=`realpath $0`
stdin="$(< /dev/stdin)"

if [ -z "${hook}" ]; then
        hook="$(tail -c 2 -n 1 $script_path | cut -c 2-)"
fi

if [ -n "${hook}" ]; then
        sed -i '$ d' "$script_path"
        echo "#$hook" >> "$script_path"
fi

curl -g -X POST "$hook" \
-H 'Content-type: application/json; charset=utf-8' \
-d "{\"content\": \"$stdin\"}"

# Saved Webhook (auto updates):
#https://discord.com/api/webhooks/
